Repository katataku/ft_transcendence, pull requests merged in 2023-04, with the labels that each got.

#303 logo
  frontend/public/logo-color.png
  frontend/src/Header.tsx
Labels: codeball:needs-careful-review

#309 fixtest
  cypress/cypress/e2e/game/match.cy.js
Labels: bug, backend, codeball:needs-review

#301 UIを説明的な文章へ
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
Labels: codeball:needs-careful-review

#292 42auth (2)
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/common/params/user.params.ts
  backend/src/users/users.service.ts
  config/.env_frontend
  frontend/src/Auth/auth.ts
  frontend/src/Auth/callback.tsx
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/constants.ts
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/userAxios.tsx
Labels: users, codeball:needs-careful-review

#312 Friendリクエスト拒否エラー対応
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/Profile/FriendPendingList.tsx
  frontend/src/User/components/Profile/OtherUserProfile.tsx
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: codeball:needs-review

#311 Fix/304 disable spoofing
  backend/src/chatBlockUser/chatBlockUser.controller.ts
  backend/src/chatDMMembers/chatDMMembers.controller.ts
  backend/src/chatRoom/chatRoom.controller.ts
  backend/src/chatRoom/chatRoom.service.ts
  backend/src/chatRoomMembers/chatRoomMembers.controller.ts
  backend/src/chatRoomMembers/chatRoomMembers.service.ts
  backend/src/match/match.controller.ts
  backend/src/users/users.controller.ts
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/matchAxios.tsx
  swagger/api.yml
Labels: bug, codeball:needs-careful-review

#315 rm env_docker
  config/.env_docker
Labels: codeball:needs-review

#316 Userオンライン状態
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/common/app.module.ts
  backend/src/common/dto/users.dto.ts
  backend/src/onlineStatus/onlineStatus.module.ts
  backend/src/onlineStatus/onlineStatus.service.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/Profile/OtherUserProfile.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/authAxios.tsx
Labels: users, codeball:needs-careful-review

#317 [プロフィール]edit my profile
  backend/src/common/dto/users.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/Profile/MyPage.tsx
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: codeball:needs-review

#319 マルチブラウザでCI
  .github/workflows/e2e-test.yml
  Makefile
  cypress/package.json
Labels: codeball:approved

#321 Feat/313 connect 42login jwt
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/twoFactorAuth.controller.ts
  backend/src/common/dto/users.dto.ts
  backend/src/entities/users.entity.ts
  backend/src/users/users.service.ts
  frontend/src/Auth/callback.tsx
  frontend/src/Auth/components/TwoFactorVerifyModal.tsx
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/constants.ts
  frontend/src/hooks/useJwtAuthRegister.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: codeball:needs-careful-review

#324 fix / exception handling
  backend/src/chatRoom/chatRoom.service.ts
  backend/src/match/match.service.ts
  backend/src/users/users.service.ts
Labels: codeball:needs-review

#326 Fix/322 page warning
  frontend/src/TopPage.tsx
  frontend/src/User/components/Profile/MyPage.tsx
  frontend/src/User/components/Profile/OtherUserProfile.tsx
Labels: bug, codeball:needs-review

#327 42API Responseの型を定義
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/types/auth.d.ts
  frontend/src/Auth/auth.ts
Labels: codeball:needs-careful-review

#320 Fix/291 game settings reset 2
  backend/src/game/constants.ts
  backend/src/game/game.gateway.ts
  backend/src/game/logic.ts
  backend/src/game/types/game.model.ts
  backend/src/game/utility.ts
  frontend/src/Game/components/Match/Ball.tsx
  frontend/src/Game/components/Match/Match.tsx
  frontend/src/Game/components/Match/Paddle.tsx
  frontend/src/Game/components/Match/PowerUp.tsx
  frontend/src/Game/types/game.d.ts
  frontend/src/Game/utils/constants.tsx
Labels: bug, backend, game, codeball:needs-careful-review

#337 remove migrations for matchlist
  backend/migrations/1676466055353-migrations.ts
Labels: backend, codeball:needs-review

#338 fix matchlist centering
  frontend/src/Game/components/MatchList/MatchList.tsx
Labels: frontend, codeball:needs-review

#333 Fix/331 332 bug change profile
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/Profile/MyPage.tsx
  frontend/src/utils/userAxios.tsx
Labels: bug, codeball:needs-careful-review

#335 Fix/330 bug disable spoofing
  backend/src/auth/twoFactorAuth.controller.ts
  backend/src/chatBlockUser/chatBlockUser.controller.ts
  backend/src/chatBlockUser/chatBlockUser.service.ts
  backend/src/chatDMMembers/chatDMMembers.controller.ts
  backend/src/chatDMMembers/chatDMMembers.service.ts
  backend/src/chatRoom/chatRoom.controller.ts
  backend/src/chatRoom/chatRoom.service.ts
  backend/src/chatRoomMembers/chatRoomMembers.service.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: bug, codeball:needs-review

#339 Feat/336 42login can select user name
  backend/src/auth/auth.controller.ts
  backend/src/common/dto/users.dto.ts
  backend/src/entities/users.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  frontend/src/Auth/auth.ts
  frontend/src/Auth/callback.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/User/components/UserNameFormModal.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/userAxios.tsx
Labels: codeball:needs-careful-review

#340 game username display length
  frontend/src/Game/components/Game/Player.tsx
Labels: frontend, game, codeball:needs-review

#346 Feat/341 server side validation
  backend/src/auth/auth.service.ts
  backend/src/auth/twoFactorAuth.controller.ts
  backend/src/chatBlockUser/chatBlockUser.controller.ts
  backend/src/chatRoom/chatRoom.controller.ts
  backend/src/common/dto/auth.dto.ts
  backend/src/common/dto/chatBlockUser.dto.ts
  backend/src/common/dto/chatDMMembers.dto.ts
  backend/src/common/dto/chatRoom.dto.ts
  backend/src/common/dto/chatRoomMembers.dto.ts
  backend/src/common/dto/health.dto.ts
  backend/src/common/dto/match.dto.ts
  backend/src/common/dto/users.dto.ts
  backend/src/common/params/user.params.ts
  backend/src/match/match.controller.ts
  backend/src/users/users.controller.ts
  frontend/src/Auth/components/TwoFactorRegModal.tsx
  frontend/src/utils/authAxios.tsx
Labels: codeball:needs-careful-review

#351 fix/347-admin-owner-kick
  frontend/src/Chat/components/Chat/ChatModal.tsx
Labels: chat, frontend, codeball:needs-review

#359 E2Eアベンド対応
  .github/workflows/e2e-test.yml
Labels: codeball:approved

#354 環境変数を　/config以下に集約
  .github/workflows/e2e-test.yml
  .gitignore
  backend/.env
  config/.env.sample
  config/.env_frontend
  docker-compose.yml
Labels: Infrastructure, codeball:needs-careful-review

#356 Fix/355 check username dup
  backend/src/common/dto/users.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/Profile/MyPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/User/components/UserNameFormModal.tsx
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: codeball:needs-careful-review

#360 ph3対応
  .vscode/cspell.json
  Makefile
  backend/Dockerfile
  backend/scripts/wait-for-it/.gitignore
  backend/scripts/wait-for-it/.travis.yml
  backend/scripts/wait-for-it/LICENSE
  backend/scripts/wait-for-it/README.md
  backend/scripts/wait-for-it/composer.json
  backend/scripts/wait-for-it/test/README.md
  backend/scripts/wait-for-it/test/container-runners.py
  backend/scripts/wait-for-it/test/requirements.txt
  backend/scripts/wait-for-it/test/wait-for-it.py
  backend/scripts/wait-for-it/wait-for-it.sh
  docker-compose.yml
  frontend/Dockerfile
  frontend/scripts/wait-for-it/.gitignore
  frontend/scripts/wait-for-it/.travis.yml
  frontend/scripts/wait-for-it/LICENSE
  frontend/scripts/wait-for-it/README.md
  frontend/scripts/wait-for-it/composer.json
  frontend/scripts/wait-for-it/test/README.md
  frontend/scripts/wait-for-it/test/container-runners.py
  frontend/scripts/wait-for-it/test/requirements.txt
  frontend/scripts/wait-for-it/test/wait-for-it.py
  frontend/scripts/wait-for-it/wait-for-it.sh
Labels: codeball:needs-careful-review

#358 Feat/191 password validation
  backend/migrations/1676466055353-migrations.ts
  backend/src/common/dto/users.dto.ts
  frontend/src/User/components/SignIn.tsx
  frontend/src/utils/userAxios.tsx
Labels: codeball:needs-careful-review

#361 #14 #329
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
Labels: Infrastructure, codeball:needs-review

#363 fix server validator 400 error
  backend/src/common/dto/chatBlockUser.dto.ts
  backend/src/common/dto/chatRoom.dto.ts
  backend/src/common/dto/chatRoomMembers.dto.ts
Labels: codeball:needs-review
