Repository katataku/ft_transcendence, pull requests merged in 2023-03, with the labels that each got.

#164 [User] Profile用の画像読み込み
  frontend/src/User/Resistration.tsx
  frontend/src/types/Chat.d.ts
  frontend/src/types/User.d.ts
Labels: frontend, users

#148 fix gameboard size
  backend/src/game/game.gateway.ts
  frontend/src/Game/assets/styles.css
  frontend/src/Game/components/Game.tsx
Labels: bug, frontend, game

#169 [チャット]URL rename
  backend/src/chatRoom/chatRoom.controller.ts
  backend/src/chatRoom/chatRoom.service.ts
  frontend/src/Chat/components/ChatList/EnterButton.tsx
  frontend/src/Chat/types/ChatList.d.ts
  frontend/src/utils/chatRoomAxios.tsx
  swagger/api.yml
Labels: chat

#167 [User] 画像をDBに保存
  backend/src/common/app.module.ts
  backend/src/common/dto/users.dto.ts
  backend/src/entities/users.entity.ts
  backend/src/main.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  frontend/src/User/Resistration.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: feature, backend, users

#174 [User] Login用のFrontend && userContext
  frontend/src/App.tsx
  frontend/src/TopPage.tsx
  frontend/src/User/Resistration.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/User/constants.ts
  frontend/src/User/functions/user.functions.ts
  frontend/src/index.tsx
  frontend/src/types/common.d.ts
  frontend/src/utils/userAxios.tsx
Labels: frontend, users

#180 [User] Sign In
  backend/src/common/dto/users.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/SignIn.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: feature, users

#190 [Front] login状態保持
  frontend/src/App.tsx
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/utils/userAxios.tsx
Labels: frontend

#207 [User] Avatarの取得方法の変更
  backend/src/users/users.controller.ts
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/User/constants.ts
  frontend/src/constants.ts
  frontend/src/img/defaultAvatar.png
  frontend/src/img/png.d.ts
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: users

#210 [add] matching system, disconnect
  backend/src/game/constants.ts
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/game/logic.ts
  backend/src/game/types/game.model.ts
  backend/src/game/utility.ts
  frontend/src/Game/components/Game/Game.tsx
  frontend/src/Game/components/Game/Player.tsx
  frontend/src/Game/components/Match/Match.tsx
  frontend/src/Game/components/Match/Paddle.tsx
  frontend/src/Game/components/Match/SpeedPU.tsx
Labels: backend, game

#228 [User] Online Status
  backend/src/common/app.module.ts
  backend/src/onlineStatus/index.ts
  backend/src/onlineStatus/onlineStatus.module.ts
  backend/src/onlineStatus/onlineStatus.service.ts
Labels: feature, users

#240 [インフラ]Codeball.aiの導入
  .github/workflows/codeball-dry-run.yml
  .vscode/cspell.json
Labels: codeball:needs-review

#247 spellチェックの範囲拡大
  .github/workflows/spell-check.yml
  .vscode/cspell.json
  Makefile
Labels: codeball:needs-review

#248 [チャット][BUG]kickされた後のアラートを消しても、ブラウザリロードするとアラートが再度表示される
  frontend/src/Chat/components/Chat/Chat.tsx
  frontend/src/Chat/components/ChatList/AlertElement.tsx
  frontend/src/Chat/components/ChatList/ChatList.tsx
  frontend/src/Chat/components/ChatRoom/ChatRoom.tsx
  frontend/src/TopPage.tsx
  frontend/src/constants.ts
  frontend/src/types/Chat.d.ts
Labels: codeball:needs-review

#250 [チャット][BUG]kick機能を全ユーザが利用できる。
  frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
  frontend/src/Chat/components/Chat/ChatModal.tsx
Labels: codeball:needs-review

#254 #224 match history on profile
  backend/src/users/users.controller.ts
  frontend/src/Game/components/Game/Player.tsx
  frontend/src/User/components/Profile/MyPage.tsx
  frontend/src/User/components/Profile/OtherUserProfile.tsx
  frontend/src/components/MatchHistory.tsx
  frontend/src/types/User.d.ts
  frontend/src/utils/userAxios.tsx
Labels: codeball:needs-review

#255 Feat/253 match UI
  backend/src/game/constants.ts
  backend/src/game/logic.ts
  frontend/src/Game/components/Game/Game.tsx
Labels: frontend, game, codeball:needs-careful-review

#259 [User] 42Auth
  backend/.env
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/index.ts
  backend/src/common/app.module.ts
  backend/src/common/params/user.params.ts
  backend/src/main.ts
  config/.env_frontend
  frontend/src/App.tsx
  frontend/src/Auth/auth.ts
  frontend/src/Auth/callback.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/utils/authAxios.ts
  swagger/api.yml
Labels: feature, frontend, backend, users, codeball:needs-careful-review

#261 Feat/257 customize paddle
  .vscode/cspell.json
  backend/src/game/constants.ts
  backend/src/game/game.gateway.ts
  backend/src/game/logic.ts
  backend/src/game/types/game.model.ts
  backend/src/game/utility.ts
  frontend/src/Game/components/Match/Ball.tsx
  frontend/src/Game/components/Match/Match.tsx
  frontend/src/Game/components/Match/Paddle.tsx
  frontend/src/Game/components/Match/PowerUp.tsx
  frontend/src/Game/components/Match/SpeedPU.tsx
  frontend/src/Game/utils/constants.tsx
Labels: codeball:needs-careful-review

#265 [プロフィール]名前重複確認用API
  backend/src/common/dto/users.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  swagger/api.yml
Labels: codeball:needs-review

#263 fix/262-ball-nan
  backend/src/game/constants.ts
  backend/src/game/logic.ts
  backend/src/game/utility.ts
Labels: codeball:needs-review

#264 feat/257-powerup-front-restru
  backend/src/game/constants.ts
  backend/src/game/game.gateway.ts
  backend/src/game/logic.ts
  backend/src/game/types/game.model.ts
  backend/src/game/utility.ts
  frontend/src/Game/assets/styles.css
  frontend/src/Game/components/Game/Game.tsx
  frontend/src/Game/components/Game/Player.tsx
  frontend/src/Game/components/Match/Match.tsx
  frontend/src/Game/components/Match/PowerUp.tsx
  frontend/src/Game/utils/constants.tsx
Labels: codeball:needs-careful-review

#270 fix/266-self-matching
  backend/src/game/game.gateway.ts
  frontend/src/Game/components/Game/Game.tsx
Labels: codeball:needs-review

#278 [チャット]fix namespace
  backend/src/chat/chat.gateway.ts
  frontend/src/Chat/components/Chat/Chat.tsx
Labels: codeball:needs-review

#276 [BUG][プロフィール]フレンドリスト更新
  frontend/src/User/components/Profile/FriendList.tsx
  frontend/src/User/components/Profile/MyPage.tsx
Labels: codeball:needs-review

#279 Fix/277 login from id to username
  backend/src/common/dto/users.dto.ts
  backend/src/users/users.service.ts
  frontend/src/User/components/SignIn.tsx
  frontend/src/types/User.d.ts
  swagger/api.yml
Labels: users, codeball:needs-careful-review

#280 docker compose profile
  Makefile
  docker-compose.yml
Labels: codeball:needs-review

#284 Feat/269 jwt auth
  .vscode/cspell.json
  backend/.env
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/auth/strategies/jwt.strategy.ts
  backend/src/common/dto/auth.dto.ts
  config/.env_docker
  config/.env_frontend
  frontend/src/App.tsx
  frontend/src/Auth/components/TwoFactorVerifyModal.tsx
  frontend/src/PrivateRoute.tsx
  frontend/src/TopPage.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/constants.ts
  frontend/src/types/auth.d.ts
  frontend/src/types/common.d.ts
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/userAxios.tsx
  swagger/api.yml
Labels: codeball:needs-careful-review

#285 remove .env
  Makefile
Labels: codeball:approved

#290 Feat/275 2FA after login
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/twoFactorAuth.controller.ts
  backend/src/common/dto/auth.dto.ts
  frontend/src/Auth/components/TwoFactorRegModal.tsx
  frontend/src/Auth/components/TwoFactorVerifyModal.tsx
  frontend/src/User/components/SignIn.tsx
  frontend/src/types/auth.d.ts
  frontend/src/utils/authAxios.tsx
Labels: frontend, backend, codeball:needs-careful-review

#274 fix/273-two-socket-player-init
  backend/src/game/game.gateway.ts
  backend/src/game/types/game.model.ts
  frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
  frontend/src/Game/components/Game/Game.tsx
Labels: codeball:needs-careful-review

#294 Feat/283 enable auth globally
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/auth/public.decorator.ts
  backend/src/healthCheck/healthCheck.controller.ts
  backend/src/users/users.controller.ts
  frontend/src/Game/components/MatchList/MatchList.tsx
  frontend/src/utils/authAxios.tsx
  frontend/src/utils/axiosConfig.tsx
  frontend/src/utils/chatBlockUserAxios.tsx
  frontend/src/utils/chatDMAxios.tsx
  frontend/src/utils/chatRoomAxios.tsx
  frontend/src/utils/chatRoomMemberAxios.tsx
  frontend/src/utils/matchAxios.tsx
  frontend/src/utils/userAxios.tsx
Labels: codeball:needs-careful-review

#293 fix/ #286 set cooldown time for invite
  frontend/src/Chat/components/Chat/ChatMessageDisplay.tsx
Labels: codeball:needs-review

#295 fix/287-wait-render
  frontend/src/App.tsx
  frontend/src/Game/components/Game/Game.tsx
Labels: codeball:needs-review

#306 2FAの使い方。
  frontend/src/Auth/components/TwoFactorRegModal.tsx
Labels: codeball:approved

#296 simple cypress tests for game
  cypress/cypress/e2e/game/match.cy.js
  cypress/cypress/e2e/game/matchlist.cy.js
  frontend/src/Game/components/Game/Game.tsx
  frontend/src/Game/components/Game/Player.tsx
  frontend/src/TopPage.tsx
Labels: codeball:needs-careful-review

#300 [TopPage]全てのユーザプロフィールへのリンクを用意する。
  frontend/src/TopPage.tsx
Labels: codeball:needs-review
